import { readFileSync as read } from 'node:fs';
import assert from 'node:assert/strict';
import { test } from 'node:test';
const html = read('public/index.html','utf8');
const css = read('public/style.css','utf8');
const app = read('public/app.js','utf8');
const motion = read('public/motion.js','utf8');
const wrangler = read('wrangler.jsonc','utf8');
test('homepage easing and 16px reveal is included',()=>{assert.match(motion, /translateY\(\$\{y\}px\)/);assert.match(motion, /760/);assert.match(motion, /\.22,\.61,\.36,1/);});
test('motion does not run on Workers or request API',()=>{assert.doesNotMatch(motion,/fetch\(|\/api\/|env\.DB/);assert.match(wrangler,/\"run_worker_first\"/);assert.match(html,/app\.js\?v=5/);});
test('original selected state remains linked to native input',()=>{assert.match(css,/choice:has\(input:checked\)/);assert.match(app,/syncChoiceVisual/);assert.doesNotMatch(motion,/input\.checked\s*=/);});
test('accessible fallback and hidden-step guard',()=>{assert.match(motion,/prefers-reduced-motion: reduce/);assert.match(css,/@media print/);assert.match(motion,/el\.closest\('\[hidden\]'\)/);assert.match(motion,/focusin/);assert.match(motion,/pagehide/);});
test('submission API and static D1 config unchanged',()=>{assert.match(app,/fetch\('\/api\/responses'/);assert.match(wrangler,/\"binding\": \"DB\"/);assert.match(wrangler,/\"custom_domain\": true/);});
