Foreground yes
DatabaseDirectory /var/lib/clamav
LocalSocket /run/audeniq-av/clamd.sock
LocalSocketMode 660
FixStaleSocket yes
TemporaryDirectory /tmp
MaxThreads 1
MaxQueue 4
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120000
StreamMaxLength 513M
MaxFileSize 513M
MaxScanSize 1024M
MaxScanTime 90000
MaxRecursion 12
MaxFiles 1000
AlertExceedsMax yes
AlertEncrypted yes
AlertBrokenExecutables yes
HeuristicAlerts yes
ScanPDF yes
ScanOLE2 yes
ScanArchive yes
SelfCheck 30
ConcurrentDatabaseReload no
LogTime yes
LogClean no
