pub mod api;
pub mod artifacts;
pub mod auth;
pub mod catalog;
pub mod config;
pub mod contracts;
pub mod database;
pub mod ddex_ern;
pub mod ddex_validate;
pub mod ddex_xsd;
pub mod distribution;
pub mod domain;
pub mod drafts;
pub mod ern;
pub mod error;
pub mod execution;
pub mod finance;
pub mod fingerprint;
pub mod identifiers;
pub mod mockdsp;
pub mod operations;
pub mod packages;
pub mod partner_onboarding;
pub mod preflight;
pub mod preparation_model;
pub mod qc;
pub mod review;
pub mod route_plan;
pub mod routing;
pub mod royalty;
pub mod storage;
pub mod submission;
pub mod uploads;
pub mod states {
    include!(concat!(env!("OUT_DIR"), "/states.rs"));
}
