//! Free local provenance signals. Metadata is untrusted; absence is UNKNOWN.
//! This is neither an AI classifier nor a SynthID verifier.
use crate::{
    domain::sha256_json,
    qc::{CheckOutcome, CheckStatus},
};
use serde_json::{Value, json};
use std::{
    collections::BTreeSet,
    io::Read,
    path::Path,
    process::{Command, Stdio},
    time::{Duration, Instant},
};

pub const RULE_VERSION: &str = "1";
const OUTPUT_LIMIT: u64 = 256 * 1024;

/// Read provenance fields locally, with bounded output and runtime.
pub fn inspect(path: &Path) -> Value {
    let executable = std::env::var("EXIFTOOL_BIN").unwrap_or_else(|_| "exiftool".into());
    let child = Command::new(executable)
        .args([
            "-j",
            "-n",
            "-G1",
            "-s",
            "-Software",
            "-CreatorTool",
            "-DigitalSourceType",
            "-Description",
            "-Comment",
            "-Encoder",
            "-UserComment",
            "-Parameters",
            "-GenerationParameters",
            "--",
        ])
        .arg(path)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn();
    let Ok(mut child) = child else {
        return unknown("metadata reader unavailable");
    };
    let Some(stdout) = child.stdout.take() else {
        let _ = child.kill();
        let _ = child.wait();
        return unknown("metadata reader output unavailable");
    };
    let reader = std::thread::spawn(move || {
        let mut output = Vec::new();
        stdout
            .take(OUTPUT_LIMIT + 1)
            .read_to_end(&mut output)
            .map(|_| output)
    });
    let deadline = Instant::now() + Duration::from_secs(10);
    let success = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status.success(),
            Ok(None) if Instant::now() < deadline => std::thread::sleep(Duration::from_millis(10)),
            _ => {
                let _ = child.kill();
                let _ = child.wait();
                break false;
            }
        }
    };
    let Ok(Ok(bytes)) = reader.join() else {
        return unknown("metadata reader failed");
    };
    if !success || bytes.len() as u64 > OUTPUT_LIMIT {
        return unknown("metadata reader failed or exceeded limits");
    }
    match serde_json::from_slice::<Value>(&bytes) {
        Ok(Value::Array(rows)) if rows.len() == 1 => from_metadata(&rows[0]),
        _ => unknown("metadata reader returned an invalid report"),
    }
}

fn unknown(reason: &str) -> Value {
    let inspection_status = if reason.starts_with("no supported AI metadata signal") {
        "COMPLETED"
    } else {
        "FAILED"
    };
    json!({"rule_version":RULE_VERSION,"outcome":"UNKNOWN","signals":[],"inspection_status":inspection_status,
        "method":"LOCAL_UNVERIFIED_METADATA","synthid":"NOT_CHECKED","reason":reason})
}

pub fn from_metadata(metadata: &Value) -> Value {
    use unicode_normalization::UnicodeNormalization;
    let mut signals = BTreeSet::new();
    if let Some(fields) = metadata.as_object() {
        for (key, value) in fields {
            let field = key.rsplit(':').next().unwrap_or(key);
            let Some(value) = value.as_str() else {
                continue;
            };
            let normalized: String = value.nfkc().flat_map(char::to_lowercase).collect();
            if field == "DigitalSourceType"
                && [
                    "trainedalgorithmicmedia",
                    "compositewithtrainedalgorithmicmedia",
                ]
                .iter()
                .any(|s| normalized.ends_with(s))
            {
                signals.insert(format!(
                    "{field}: algorithmic media declaration (unverified)"
                ));
            }
            let generator_field = matches!(
                field,
                "Software" | "CreatorTool" | "Encoder" | "Parameters" | "GenerationParameters"
            );
            let declared_generated = [
                "generated by ",
                "generated with ",
                "created with ",
                "ai-generated",
                "ai generated",
            ]
            .iter()
            .any(|p| normalized.contains(p));
            if !generator_field && !declared_generated {
                continue;
            }
            let tokens: Vec<_> = normalized
                .split(|c: char| !c.is_alphanumeric())
                .filter(|s| !s.is_empty())
                .collect();
            for generator in [
                "suno",
                "udio",
                "midjourney",
                "chatgpt",
                "firefly",
                "lyria",
                "comfyui",
                "automatic1111",
            ] {
                if tokens.contains(&generator) {
                    signals.insert(format!(
                        "{field}: {generator} generator metadata (unverified)"
                    ));
                }
            }
            for pair in [["stable", "diffusion"], ["dall", "e"]] {
                if tokens.windows(2).any(|t| t == pair) {
                    signals.insert(format!(
                        "{field}: {} {} generator metadata (unverified)",
                        pair[0], pair[1]
                    ));
                }
            }
            if normalized.contains("ai-generated") || normalized.contains("ai generated") {
                signals.insert(format!("{field}: AI generation statement (unverified)"));
            }
        }
    }
    if signals.is_empty() {
        return unknown("no supported AI metadata signal; this is not proof of human authorship");
    }
    json!({"rule_version":RULE_VERSION,"outcome":"AI_METADATA_SIGNAL","signals":signals,"inspection_status":"COMPLETED",
        "method":"LOCAL_UNVERIFIED_METADATA","synthid":"NOT_CHECKED"})
}

pub fn outcome(code: &'static str, report: &Value) -> CheckOutcome {
    CheckOutcome {
        check_code: code,
        status: if report["inspection_status"] != "COMPLETED" {
            CheckStatus::TechnicalRetry
        } else if report["outcome"] == "AI_METADATA_SIGNAL" {
            CheckStatus::ReviewRequired
        } else {
            CheckStatus::NotApplicable
        },
        input_hash: sha256_json(report),
        detail: report.to_string(),
    }
}

/// Literal generation disclosures or copied chatbot boilerplate, never style.
pub fn lyrics_signals(lyrics: &str) -> Vec<&'static str> {
    use unicode_normalization::UnicodeNormalization;
    let text: String = lyrics.nfkc().flat_map(char::to_lowercase).collect();
    [
        "generated by chatgpt",
        "generated with chatgpt",
        "lyrics generated by ai",
        "as an ai language model",
        "chatgpt로 생성",
        "ai로 생성한 가사",
        "인공지능으로 생성한 가사",
    ]
    .into_iter()
    .filter(|marker| text.contains(marker))
    .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn absence_is_unknown_and_signals_are_review_only() {
        let r = from_metadata(
            &json!({"XMP:CreatorTool":"Stable Diffusion", "XMP:DigitalSourceType":"http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"}),
        );
        assert_eq!(r["outcome"], "AI_METADATA_SIGNAL");
        assert_eq!(r["synthid"], "NOT_CHECKED");
        assert_eq!(
            outcome("IMAGE_AI_PROVENANCE", &r).status,
            CheckStatus::ReviewRequired
        );
        for metadata in [
            json!({}),
            json!({"SourceFile":"suno-song.wav","EXIF:Software":"Adobe Photoshop","XMP:Description":"A song about Suno"}),
        ] {
            assert_eq!(from_metadata(&metadata)["outcome"], "UNKNOWN");
        }
    }
    #[test]
    fn lyrics_style_does_not_prove_ai_authorship() {
        assert!(lyrics_signals("Verse 1\nLove under the moon\nLove under the moon").is_empty());
        assert!(!lyrics_signals("Lyrics generated by AI").is_empty());
        assert!(!lyrics_signals("Ｇｅｎｅｒａｔｅｄ ｂｙ ＣｈａｔＧＰＴ").is_empty());
    }
}
