//! File-drop transports for partner delivery (F6).
//!
//! Most DSPs take DDEX deliveries as a file drop: SFTP (the industry
//! default), or an S3-compatible bucket. The adapters (`crate::partners`)
//! only see [`FileTransport`]; which wire is used comes from the partner's
//! config file.
//!
//! Visibility rule: a file appears at its final name only once it is
//! complete (SFTP uploads to `name.part` and renames; S3 PUT is atomic), so
//! a partner scanning the drop never ingests half a file.
//!
//! Errors are classified for the no-duplicate-send rule: `Unreachable`
//! means the connection failed before anything was written; `Failed` means
//! the transfer may have partially happened. The DDEX adapter turns both
//! into a safe retry as long as the completion marker was never written.
use crate::error::{Error, Result};
use crate::partner_config::{Secret, TransportConfig};
use async_trait::async_trait;
use hmac::{Hmac, KeyInit, Mac};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransportError {
    /// Nothing reached the partner (DNS, connect, auth, host key).
    Unreachable(String),
    /// The operation failed after the session was established.
    Failed(String),
    NotFound,
}

impl std::fmt::Display for TransportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unreachable(d) => write!(f, "unreachable: {d}"),
            Self::Failed(d) => write!(f, "failed: {d}"),
            Self::NotFound => f.write_str("not found"),
        }
    }
}

pub type TResult<T> = std::result::Result<T, TransportError>;

/// One upload in a batch: local source (or inline bytes) and remote path
/// relative to the transport root.
#[derive(Debug, Clone)]
pub enum Upload {
    File { local: PathBuf, remote: String },
    Bytes { bytes: Vec<u8>, remote: String },
}

impl Upload {
    pub fn remote(&self) -> &str {
        match self {
            Self::File { remote, .. } | Self::Bytes { remote, .. } => remote,
        }
    }
}

#[async_trait]
pub trait FileTransport: Send + Sync {
    /// Upload every file, creating directories as needed. Files become
    /// visible at their final names only when complete.
    async fn put_all(&self, uploads: &[Upload]) -> TResult<()>;
    /// File names (not paths) directly inside `dir`. A missing dir is empty.
    async fn list(&self, dir: &str) -> TResult<Vec<String>>;
    /// Read one (small) file: ACKs, result files.
    async fn get(&self, path: &str, max_bytes: u64) -> TResult<Vec<u8>>;
    /// Connection + authentication + root listing check.
    async fn probe(&self) -> TResult<()>;
    fn describe(&self) -> String;
}

/// Remote paths are generated by us (UPC, timestamps, codes); anything else
/// is refused rather than quoted.
pub fn valid_remote_path(p: &str) -> bool {
    !p.is_empty()
        && p.len() <= 512
        && p.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"._-/".contains(&b))
        && !p.split('/').any(|s| s == ".." || s == ".")
        && !p.contains("//")
}

pub fn join(root: &str, rel: &str) -> String {
    let root = root.trim_end_matches('/');
    let rel = rel.trim_start_matches('/');
    if root.is_empty() {
        format!("/{rel}")
    } else {
        format!("{root}/{rel}")
    }
}

fn parent_dirs(path: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let parts: Vec<&str> = path.split('/').collect();
    for (i, part) in parts.iter().enumerate() {
        if i + 1 == parts.len() {
            break;
        }
        if part.is_empty() {
            if i == 0 {
                cur.push('/');
            }
            continue;
        }
        if !cur.is_empty() && !cur.ends_with('/') {
            cur.push('/');
        }
        cur.push_str(part);
        out.push(cur.clone());
    }
    out
}

pub fn build(config: &TransportConfig) -> Result<Option<std::sync::Arc<dyn FileTransport>>> {
    Ok(Some(match config {
        TransportConfig::Sftp {
            host,
            port,
            username,
            private_key,
            known_hosts,
            remote_root,
            connect_timeout_secs,
            transfer_timeout_secs,
        } => std::sync::Arc::new(SftpTransport {
            host: host.clone(),
            port: *port,
            username: username.clone(),
            key: private_key.resolve_path("id_partner")?,
            known_hosts: known_hosts.resolve_path("known_hosts")?,
            root: remote_root.clone(),
            connect_timeout: Duration::from_secs((*connect_timeout_secs).clamp(3, 120)),
            transfer_timeout: Duration::from_secs((*transfer_timeout_secs).clamp(30, 6 * 3600)),
        }),
        TransportConfig::S3 {
            endpoint,
            region,
            bucket,
            prefix,
            access_key_id,
            secret_access_key,
        } => std::sync::Arc::new(S3Transport::new(
            endpoint,
            region,
            bucket,
            prefix,
            access_key_id.resolve()?,
            secret_access_key.resolve()?,
        )?),
        TransportConfig::Local { root } => std::sync::Arc::new(LocalTransport::new(root.clone())),
        TransportConfig::None => return Ok(None),
    }))
}

// ---------------------------------------------------------------------------
// Local directory
// ---------------------------------------------------------------------------

/// Local directory drop (staging rehearsals, tests, or a partner mount).
pub struct LocalTransport {
    root: PathBuf,
}

impl LocalTransport {
    pub fn new(root: PathBuf) -> Self {
        Self { root }
    }
    fn path(&self, rel: &str) -> TResult<PathBuf> {
        let rel = rel.trim_start_matches('/');
        if !rel.is_empty() && !valid_remote_path(rel) {
            return Err(TransportError::Failed(format!("invalid path {rel}")));
        }
        Ok(self.root.join(rel))
    }
}

#[async_trait]
impl FileTransport for LocalTransport {
    async fn put_all(&self, uploads: &[Upload]) -> TResult<()> {
        if !self.root.is_dir() {
            return Err(TransportError::Unreachable("root missing".into()));
        }
        for u in uploads {
            let dest = self.path(u.remote())?;
            if let Some(parent) = dest.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|e| TransportError::Failed(e.to_string()))?;
            }
            let part = dest.with_extension(format!(
                "{}part",
                dest.extension()
                    .map(|e| format!("{}.", e.to_string_lossy()))
                    .unwrap_or_default()
            ));
            match u {
                Upload::File { local, .. } => tokio::fs::copy(local, &part).await.map(|_| ()),
                Upload::Bytes { bytes, .. } => tokio::fs::write(&part, bytes).await,
            }
            .map_err(|e| TransportError::Failed(e.to_string()))?;
            tokio::fs::rename(&part, &dest)
                .await
                .map_err(|e| TransportError::Failed(e.to_string()))?;
        }
        Ok(())
    }
    async fn list(&self, dir: &str) -> TResult<Vec<String>> {
        let p = self.path(dir)?;
        let mut out = Vec::new();
        let mut rd = match tokio::fs::read_dir(&p).await {
            Ok(rd) => rd,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(out),
            Err(e) => return Err(TransportError::Failed(e.to_string())),
        };
        while let Some(e) = rd
            .next_entry()
            .await
            .map_err(|e| TransportError::Failed(e.to_string()))?
        {
            out.push(e.file_name().to_string_lossy().to_string());
        }
        out.sort();
        Ok(out)
    }
    async fn get(&self, path: &str, max_bytes: u64) -> TResult<Vec<u8>> {
        let p = self.path(path)?;
        match tokio::fs::metadata(&p).await {
            Ok(m) if m.len() > max_bytes => {
                return Err(TransportError::Failed("file too large".into()));
            }
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Err(TransportError::NotFound);
            }
            Err(e) => return Err(TransportError::Failed(e.to_string())),
        }
        tokio::fs::read(&p)
            .await
            .map_err(|e| TransportError::Failed(e.to_string()))
    }
    async fn probe(&self) -> TResult<()> {
        if self.root.is_dir() {
            Ok(())
        } else {
            Err(TransportError::Unreachable("root missing".into()))
        }
    }
    fn describe(&self) -> String {
        format!("file://{}", self.root.display())
    }
}

// ---------------------------------------------------------------------------
// SFTP (OpenSSH client in batch mode)
// ---------------------------------------------------------------------------

/// SFTP through the system OpenSSH client (`sftp -b -`): key auth only,
/// strict host-key checking against the pinned known_hosts, no agent, no
/// password prompts. OpenSSH is the most widely interoperable SFTP client
/// DSP ingestion servers are tested against, and keeps the crypto stack out
/// of this binary. `SFTP_BIN` overrides the executable.
pub struct SftpTransport {
    pub host: String,
    pub port: u16,
    pub username: String,
    pub key: PathBuf,
    pub known_hosts: PathBuf,
    pub root: String,
    pub connect_timeout: Duration,
    pub transfer_timeout: Duration,
}

/// Quote a local path for an sftp batch line (paths we control: temp dirs).
fn sftp_quote(s: &str) -> TResult<String> {
    if s.contains('"') || s.contains('\n') || s.contains('\\') {
        return Err(TransportError::Failed("unquotable path".into()));
    }
    Ok(format!("\"{s}\""))
}

impl SftpTransport {
    async fn run(&self, script: &str, timeout: Duration) -> TResult<String> {
        use tokio::io::AsyncWriteExt;
        let bin = std::env::var("SFTP_BIN").unwrap_or_else(|_| "sftp".into());
        let mut cmd = tokio::process::Command::new(bin);
        cmd.arg("-b")
            .arg("-")
            .arg("-q")
            .arg("-P")
            .arg(self.port.to_string())
            .arg("-i")
            .arg(&self.key)
            .arg("-o")
            .arg("BatchMode=yes")
            .arg("-o")
            .arg("IdentitiesOnly=yes")
            .arg("-o")
            .arg("StrictHostKeyChecking=yes")
            .arg("-o")
            .arg(format!("UserKnownHostsFile={}", self.known_hosts.display()))
            .arg("-o")
            .arg("GlobalKnownHostsFile=/dev/null")
            .arg("-o")
            .arg(format!("ConnectTimeout={}", self.connect_timeout.as_secs()))
            .arg("-o")
            .arg("ServerAliveInterval=15")
            .arg("-o")
            .arg("ServerAliveCountMax=4")
            .arg(format!("{}@{}", self.username, self.host))
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .kill_on_drop(true);
        let mut child = cmd
            .spawn()
            .map_err(|e| TransportError::Unreachable(format!("sftp not runnable: {e}")))?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin
                .write_all(script.as_bytes())
                .await
                .map_err(|e| TransportError::Unreachable(e.to_string()))?;
        }
        let out = tokio::time::timeout(timeout, child.wait_with_output())
            .await
            .map_err(|_| TransportError::Failed("sftp timed out".into()))?
            .map_err(|e| TransportError::Failed(e.to_string()))?;
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        if out.status.success() {
            return Ok(stdout);
        }
        let stderr: String = String::from_utf8_lossy(&out.stderr)
            .chars()
            .take(400)
            .collect();
        // ssh exits 255 when the connection itself failed (DNS, refused,
        // host key, auth): nothing was transferred. Any other failure
        // happened inside an established session.
        if out.status.code() == Some(255)
            || stderr.contains("Connection refused")
            || stderr.contains("Could not resolve")
            || stderr.contains("Permission denied")
            || stderr.contains("Host key verification failed")
            || stderr.contains("Connection closed")
                && !stdout.lines().any(|l| l.starts_with("sftp>"))
        {
            Err(TransportError::Unreachable(stderr))
        } else if stderr.contains("No such file") || stderr.contains("not found") {
            Err(TransportError::NotFound)
        } else {
            Err(TransportError::Failed(stderr))
        }
    }
}

#[async_trait]
impl FileTransport for SftpTransport {
    async fn put_all(&self, uploads: &[Upload]) -> TResult<()> {
        let tmp = tempdir()?;
        let mut script = String::new();
        let mut made = std::collections::BTreeSet::new();
        for (i, u) in uploads.iter().enumerate() {
            if !valid_remote_path(u.remote().trim_start_matches('/')) {
                return Err(TransportError::Failed(format!(
                    "invalid remote path {}",
                    u.remote()
                )));
            }
            let remote = join(&self.root, u.remote());
            for d in parent_dirs(&remote) {
                if made.insert(d.clone()) {
                    // '-' prefix: an existing directory is not an error.
                    script.push_str(&format!("-mkdir {d}\n"));
                }
            }
            let local = match u {
                Upload::File { local, .. } => local.clone(),
                Upload::Bytes { bytes, .. } => {
                    let p = tmp.join(format!("inline-{i}"));
                    tokio::fs::write(&p, bytes)
                        .await
                        .map_err(|e| TransportError::Failed(e.to_string()))?;
                    p
                }
            };
            let local = sftp_quote(&local.to_string_lossy())?;
            // Upload under .part, then rename: the partner never sees a
            // partial file at its final name. A stale final name from an
            // earlier failed attempt is removed first ('-': may not exist).
            script.push_str(&format!("put {local} {remote}.part\n"));
            script.push_str(&format!("-rm {remote}\n"));
            script.push_str(&format!("rename {remote}.part {remote}\n"));
        }
        let r = self.run(&script, self.transfer_timeout).await;
        let _ = tokio::fs::remove_dir_all(&tmp).await;
        r.map(|_| ())
    }
    async fn list(&self, dir: &str) -> TResult<Vec<String>> {
        let rel = dir.trim_start_matches('/');
        if !rel.is_empty() && !valid_remote_path(rel) {
            return Err(TransportError::Failed("invalid path".into()));
        }
        let path = if rel.is_empty() {
            self.root.clone()
        } else {
            join(&self.root, rel)
        };
        // '-ls': a missing directory is an empty listing, not an error.
        let out = self
            .run(&format!("-ls -1 {path}\n"), self.connect_timeout * 3)
            .await?;
        let mut names: Vec<String> = out
            .lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with("sftp>") && !l.contains("not found"))
            .filter_map(|l| l.rsplit('/').next().map(str::to_string))
            .filter(|n| n != "." && n != "..")
            .collect();
        names.sort();
        names.dedup();
        Ok(names)
    }
    async fn get(&self, path: &str, max_bytes: u64) -> TResult<Vec<u8>> {
        let rel = path.trim_start_matches('/');
        if !valid_remote_path(rel) {
            return Err(TransportError::Failed("invalid path".into()));
        }
        let tmp = tempdir()?;
        let local = tmp.join("download");
        let script = format!(
            "get {} {}\n",
            join(&self.root, rel),
            sftp_quote(&local.to_string_lossy())?
        );
        let r = self.run(&script, self.connect_timeout * 3).await;
        let bytes = match r {
            Ok(_) => match tokio::fs::metadata(&local).await {
                Ok(m) if m.len() > max_bytes => {
                    Err(TransportError::Failed("file too large".into()))
                }
                Ok(_) => tokio::fs::read(&local)
                    .await
                    .map_err(|e| TransportError::Failed(e.to_string())),
                Err(_) => Err(TransportError::NotFound),
            },
            Err(e) => Err(e),
        };
        let _ = tokio::fs::remove_dir_all(&tmp).await;
        bytes
    }
    async fn probe(&self) -> TResult<()> {
        self.run(&format!("ls -1 {}\n", self.root), self.connect_timeout * 3)
            .await
            .map(|_| ())
    }
    fn describe(&self) -> String {
        format!(
            "sftp://{}@{}:{}{}",
            self.username, self.host, self.port, self.root
        )
    }
}

fn tempdir() -> TResult<PathBuf> {
    let p = std::env::temp_dir().join(format!("audeniq-xfer-{}", uuid::Uuid::new_v4().simple()));
    std::fs::create_dir_all(&p).map_err(|e| TransportError::Failed(e.to_string()))?;
    Ok(p)
}

// ---------------------------------------------------------------------------
// S3-compatible bucket
// ---------------------------------------------------------------------------

/// A partner-owned S3-compatible bucket (AWS S3, GCS interop, R2, MinIO),
/// SigV4 presigned requests.
pub struct S3Transport {
    endpoint: url::Url,
    region: String,
    bucket: String,
    prefix: String,
    access: Secret,
    secret: Secret,
    client: reqwest::Client,
}

fn uri_enc(s: &str, keep_slash: bool) -> String {
    s.bytes()
        .map(|b| {
            if b.is_ascii_alphanumeric() || b"-_.~".contains(&b) || (keep_slash && b == b'/') {
                (b as char).to_string()
            } else {
                format!("%{b:02X}")
            }
        })
        .collect()
}

impl S3Transport {
    pub fn new(
        endpoint: &str,
        region: &str,
        bucket: &str,
        prefix: &str,
        access: Secret,
        secret: Secret,
    ) -> Result<Self> {
        let endpoint =
            url::Url::parse(endpoint).map_err(|_| Error::InvalidCode("PARTNER_URL_INVALID"))?;
        let local = std::env::var("AUDENIQ_ALLOW_LOCAL_PARTNER_TRANSPORT").as_deref() == Ok("true")
            && endpoint.scheme() == "http";
        if (endpoint.scheme() != "https" && !local)
            || endpoint.host_str().is_none()
            || bucket.is_empty()
            || !bucket
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b".-".contains(&b))
            || (!prefix.is_empty() && !valid_remote_path(prefix.trim_matches('/')))
        {
            return Err(Error::InvalidCode("PARTNER_URL_INVALID"));
        }
        Ok(Self {
            endpoint,
            region: region.to_string(),
            bucket: bucket.to_string(),
            prefix: prefix.trim_matches('/').to_string(),
            access,
            secret,
            client: reqwest::Client::builder()
                .connect_timeout(Duration::from_secs(15))
                .read_timeout(Duration::from_secs(60))
                .timeout(Duration::from_secs(3600))
                .redirect(reqwest::redirect::Policy::none())
                .build()
                .map_err(|_| Error::Internal)?,
        })
    }

    fn key(&self, rel: &str) -> String {
        let rel = rel.trim_start_matches('/');
        if self.prefix.is_empty() {
            rel.to_string()
        } else {
            format!("{}/{rel}", self.prefix)
        }
    }

    /// SigV4 query-string presign (path-style), with extra query params.
    pub fn presign(
        &self,
        method: &str,
        key: &str,
        extra_query: &BTreeMap<String, String>,
        signed_headers: &BTreeMap<String, String>,
        at: chrono::DateTime<chrono::Utc>,
    ) -> String {
        let path = if key.is_empty() {
            format!("/{}", self.bucket)
        } else {
            format!("/{}/{}", self.bucket, uri_enc(key, true))
        };
        let host = self.endpoint[url::Position::BeforeHost..url::Position::AfterPort].to_string();
        let mut headers = signed_headers.clone();
        headers.insert("host".into(), host.clone());
        let names = headers.keys().cloned().collect::<Vec<_>>().join(";");
        let canonical_headers: String = headers
            .iter()
            .map(|(k, v)| format!("{k}:{}\n", v.trim()))
            .collect();
        let date = at.format("%Y%m%d").to_string();
        let datetime = at.format("%Y%m%dT%H%M%SZ").to_string();
        let scope = format!("{date}/{}/s3/aws4_request", self.region);
        let mut q: BTreeMap<String, String> = extra_query.clone();
        q.insert("X-Amz-Algorithm".into(), "AWS4-HMAC-SHA256".into());
        q.insert(
            "X-Amz-Credential".into(),
            format!("{}/{scope}", self.access.expose()),
        );
        q.insert("X-Amz-Date".into(), datetime.clone());
        q.insert("X-Amz-Expires".into(), "900".into());
        q.insert("X-Amz-SignedHeaders".into(), names.clone());
        let query = q
            .iter()
            .map(|(k, v)| format!("{}={}", uri_enc(k, false), uri_enc(v, false)))
            .collect::<Vec<_>>()
            .join("&");
        let canonical =
            format!("{method}\n{path}\n{query}\n{canonical_headers}\n{names}\nUNSIGNED-PAYLOAD");
        let to_sign = format!(
            "AWS4-HMAC-SHA256\n{datetime}\n{scope}\n{}",
            hex::encode(Sha256::digest(canonical.as_bytes()))
        );
        let h = |k: &[u8], s: &str| {
            let mut m = Hmac::<Sha256>::new_from_slice(k).expect("hmac key");
            m.update(s.as_bytes());
            m.finalize().into_bytes().to_vec()
        };
        let k = h(format!("AWS4{}", self.secret.expose()).as_bytes(), &date);
        let k = h(&k, &self.region);
        let k = h(&k, "s3");
        let k = h(&k, "aws4_request");
        format!(
            "{}://{host}{path}?{query}&X-Amz-Signature={}",
            self.endpoint.scheme(),
            hex::encode(h(&k, &to_sign))
        )
    }

    fn classify(e: reqwest::Error) -> TransportError {
        if e.is_connect() || e.is_builder() {
            TransportError::Unreachable(e.to_string())
        } else {
            TransportError::Failed(e.to_string())
        }
    }

    async fn put_body(&self, key: &str, body: reqwest::Body, len: u64) -> TResult<()> {
        let headers = BTreeMap::from([("content-length".to_string(), len.to_string())]);
        let url = self.presign("PUT", key, &BTreeMap::new(), &headers, chrono::Utc::now());
        let r = self
            .client
            .put(url)
            .header("content-length", len)
            .body(body)
            .send()
            .await
            .map_err(Self::classify)?;
        match r.status().as_u16() {
            200..=299 => Ok(()),
            401 | 403 => Err(TransportError::Unreachable(format!("S3 {}", r.status()))),
            s => Err(TransportError::Failed(format!("S3 PUT {s}"))),
        }
    }
}

#[async_trait]
impl FileTransport for S3Transport {
    async fn put_all(&self, uploads: &[Upload]) -> TResult<()> {
        for u in uploads {
            if !valid_remote_path(u.remote().trim_start_matches('/')) {
                return Err(TransportError::Failed("invalid remote path".into()));
            }
            let key = self.key(u.remote());
            match u {
                Upload::File { local, .. } => {
                    let f = tokio::fs::File::open(local)
                        .await
                        .map_err(|e| TransportError::Failed(e.to_string()))?;
                    let len = f
                        .metadata()
                        .await
                        .map_err(|e| TransportError::Failed(e.to_string()))?
                        .len();
                    self.put_body(&key, reqwest::Body::from(f), len).await?;
                }
                Upload::Bytes { bytes, .. } => {
                    self.put_body(&key, reqwest::Body::from(bytes.clone()), bytes.len() as u64)
                        .await?;
                }
            }
        }
        Ok(())
    }
    async fn list(&self, dir: &str) -> TResult<Vec<String>> {
        let rel = dir.trim_matches('/');
        let prefix = if rel.is_empty() {
            if self.prefix.is_empty() {
                String::new()
            } else {
                format!("{}/", self.prefix)
            }
        } else {
            format!("{}/", self.key(rel))
        };
        let mut names = Vec::new();
        let mut token: Option<String> = None;
        for _ in 0..50 {
            let mut q = BTreeMap::from([
                ("list-type".to_string(), "2".to_string()),
                ("prefix".to_string(), prefix.clone()),
                ("delimiter".to_string(), "/".to_string()),
            ]);
            if let Some(t) = &token {
                q.insert("continuation-token".into(), t.clone());
            }
            let url = self.presign("GET", "", &q, &BTreeMap::new(), chrono::Utc::now());
            let r = self.client.get(url).send().await.map_err(Self::classify)?;
            if !r.status().is_success() {
                return Err(TransportError::Failed(format!("S3 LIST {}", r.status())));
            }
            let body = r
                .text()
                .await
                .map_err(|e| TransportError::Failed(e.to_string()))?;
            for tag in ["Key", "Prefix"] {
                for v in xml_values(&body, tag) {
                    if let Some(rest) = v.strip_prefix(&prefix) {
                        let n = rest.trim_end_matches('/');
                        if !n.is_empty() && !n.contains('/') {
                            names.push(n.to_string());
                        }
                    }
                }
            }
            token = xml_values(&body, "NextContinuationToken")
                .into_iter()
                .next();
            if token.is_none() {
                break;
            }
        }
        names.sort();
        names.dedup();
        Ok(names)
    }
    async fn get(&self, path: &str, max_bytes: u64) -> TResult<Vec<u8>> {
        let url = self.presign(
            "GET",
            &self.key(path),
            &BTreeMap::new(),
            &BTreeMap::new(),
            chrono::Utc::now(),
        );
        let mut r = self.client.get(url).send().await.map_err(Self::classify)?;
        if r.status() == reqwest::StatusCode::NOT_FOUND {
            return Err(TransportError::NotFound);
        }
        if !r.status().is_success() {
            return Err(TransportError::Failed(format!("S3 GET {}", r.status())));
        }
        let mut out = Vec::new();
        while let Some(c) = r
            .chunk()
            .await
            .map_err(|e| TransportError::Failed(e.to_string()))?
        {
            if (out.len() + c.len()) as u64 > max_bytes {
                return Err(TransportError::Failed("file too large".into()));
            }
            out.extend_from_slice(&c);
        }
        Ok(out)
    }
    async fn probe(&self) -> TResult<()> {
        let q = BTreeMap::from([
            ("list-type".to_string(), "2".to_string()),
            ("max-keys".to_string(), "1".to_string()),
        ]);
        let url = self.presign("GET", "", &q, &BTreeMap::new(), chrono::Utc::now());
        let r = self.client.get(url).send().await.map_err(Self::classify)?;
        if r.status().is_success() {
            Ok(())
        } else {
            Err(TransportError::Unreachable(format!("S3 {}", r.status())))
        }
    }
    fn describe(&self) -> String {
        format!("s3://{}/{}", self.bucket, self.prefix)
    }
}

/// Text of every `<tag>…</tag>` (XML-unescaped), namespace-agnostic.
pub fn xml_values(xml: &str, tag: &str) -> Vec<String> {
    use quick_xml::events::Event;
    let mut r = quick_xml::Reader::from_str(xml);
    let mut out = Vec::new();
    let mut inside = false;
    let mut buf = String::new();
    loop {
        match r.read_event() {
            Ok(Event::Start(e)) if e.local_name().as_ref() == tag => {
                inside = true;
                buf.clear();
            }
            Ok(Event::Text(t)) if inside => {
                let raw = t.into_inner();
                buf.push_str(&quick_xml::escape::unescape(&raw).unwrap_or(raw.clone()));
            }
            Ok(Event::CData(t)) if inside => buf.push_str(&t.into_inner()),
            Ok(Event::GeneralRef(g)) if inside => {
                if let Ok(Some(c)) = g.resolve_char_ref() {
                    buf.push(c);
                } else {
                    let ent = format!("&{};", g.into_inner());
                    buf.push_str(&quick_xml::escape::unescape(&ent).unwrap_or_default());
                }
            }
            Ok(Event::End(e)) if inside && e.local_name().as_ref() == tag => {
                inside = false;
                out.push(buf.trim().to_string());
            }
            Ok(Event::Eof) | Err(_) => break,
            _ => {}
        }
    }
    out
}

/// Probe without a full adapter (admin CLI connectivity check).
pub async fn probe_config(config: &TransportConfig) -> Result<String> {
    match build(config)? {
        Some(t) => match t.probe().await {
            Ok(()) => Ok(t.describe()),
            Err(e) => {
                tracing::warn!(target = %t.describe(), error = %e, "partner transport probe failed");
                Err(Error::PolicyGate("PARTNER_TRANSPORT_UNREACHABLE"))
            }
        },
        None => Ok("no file transport".into()),
    }
}

pub fn file_name(path: &Path) -> String {
    path.file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn remote_paths_are_strict() {
        for ok in [
            "a/b.xml",
            "20260101_1/8800000000001/x.flac",
            "BatchComplete_1.xml",
        ] {
            assert!(valid_remote_path(ok), "{ok}");
        }
        for bad in ["", "../x", "a/../b", "a//b", "a b", "a;b", "a\nb", "./a"] {
            assert!(!valid_remote_path(bad), "{bad:?}");
        }
    }

    #[test]
    fn parent_dirs_are_listed_outermost_first() {
        assert_eq!(
            parent_dirs("/inbox/b1/upc/x.xml"),
            vec!["/inbox", "/inbox/b1", "/inbox/b1/upc"]
        );
        assert_eq!(parent_dirs("b1/x"), vec!["b1"]);
        assert_eq!(join("/inbox/", "/b1/x"), "/inbox/b1/x");
        assert_eq!(join("/", "b1"), "/b1");
    }

    #[test]
    fn xml_values_are_namespace_agnostic_and_unescaped() {
        let x = r#"<a:R xmlns:a="u"><a:Key>p/one&amp;two</a:Key><Key>p/b</Key><Prefix>p/c/</Prefix></a:R>"#;
        assert_eq!(xml_values(x, "Key"), vec!["p/one&two", "p/b"]);
        assert_eq!(xml_values(x, "Prefix"), vec!["p/c/"]);
    }

    #[tokio::test]
    async fn local_transport_round_trips_and_hides_partial_files() {
        let root = std::env::temp_dir().join(format!("audeniq-lt-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&root).unwrap();
        let t = LocalTransport::new(root.clone());
        t.put_all(&[Upload::Bytes {
            bytes: b"<x/>".to_vec(),
            remote: "b1/u/u.xml".into(),
        }])
        .await
        .unwrap();
        assert_eq!(t.list("b1/u").await.unwrap(), vec!["u.xml"]);
        assert_eq!(t.get("b1/u/u.xml", 10).await.unwrap(), b"<x/>");
        assert!(t.get("b1/u/u.xml", 2).await.is_err());
        assert_eq!(t.get("b1/none", 10).await, Err(TransportError::NotFound));
        assert!(t.list("missing").await.unwrap().is_empty());
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn s3_presign_is_deterministic_and_scoped() {
        let t = S3Transport::new(
            "https://s3.example.com",
            "us-east-1",
            "partner-inbox",
            "audeniq",
            Secret::from_value("AKID"),
            Secret::from_value("secret"),
        )
        .unwrap();
        let at = chrono::DateTime::parse_from_rfc3339("2026-01-01T00:00:00Z")
            .unwrap()
            .to_utc();
        let a = t.presign(
            "PUT",
            "audeniq/a.xml",
            &BTreeMap::new(),
            &BTreeMap::new(),
            at,
        );
        assert!(a.starts_with("https://s3.example.com/partner-inbox/audeniq/a.xml?"));
        assert!(a.contains("X-Amz-Credential=AKID%2F20260101%2Fus-east-1%2Fs3%2Faws4_request"));
        assert_ne!(
            a,
            t.presign(
                "GET",
                "audeniq/a.xml",
                &BTreeMap::new(),
                &BTreeMap::new(),
                at
            )
        );
        assert!(
            S3Transport::new(
                "http://s3.example.com",
                "r",
                "b",
                "",
                Secret::default(),
                Secret::default()
            )
            .is_err()
        );
    }
}

/// Real SFTP round trip against a test server. Opt-in: set SFTP_TEST_HOST,
/// SFTP_TEST_PORT, SFTP_TEST_USER, SFTP_TEST_KEY, SFTP_TEST_KNOWN_HOSTS and
/// SFTP_TEST_ROOT (CI starts a throwaway sshd for this).
#[cfg(test)]
mod sftp_tests {
    use super::*;

    fn from_env() -> Option<SftpTransport> {
        let v = |k: &str| std::env::var(k).ok().filter(|s| !s.is_empty());
        Some(SftpTransport {
            host: v("SFTP_TEST_HOST")?,
            port: v("SFTP_TEST_PORT")?.parse().ok()?,
            username: v("SFTP_TEST_USER")?,
            key: v("SFTP_TEST_KEY")?.into(),
            known_hosts: v("SFTP_TEST_KNOWN_HOSTS")?.into(),
            root: v("SFTP_TEST_ROOT")?,
            connect_timeout: Duration::from_secs(10),
            transfer_timeout: Duration::from_secs(60),
        })
    }

    #[tokio::test]
    async fn sftp_upload_list_get_and_unreachable() {
        let Some(t) = from_env() else {
            eprintln!("SFTP_TEST_* not set: real SFTP round trip not run");
            return;
        };
        t.probe().await.unwrap();
        let batch = format!("t{}", uuid::Uuid::new_v4().simple());
        let local = std::env::temp_dir().join(format!("{batch}.bin"));
        std::fs::write(&local, vec![7u8; 300_000]).unwrap();
        t.put_all(&[
            Upload::File {
                local: local.clone(),
                remote: format!("{batch}/upc/upc_01_001.flac"),
            },
            Upload::Bytes {
                bytes: b"<x/>".to_vec(),
                remote: format!("{batch}/upc/upc.xml"),
            },
        ])
        .await
        .unwrap();
        // Re-upload over an existing final name works (stale file removed).
        t.put_all(&[Upload::Bytes {
            bytes: b"<y/>".to_vec(),
            remote: format!("{batch}/upc/upc.xml"),
        }])
        .await
        .unwrap();
        assert_eq!(
            t.list(&format!("{batch}/upc")).await.unwrap(),
            vec!["upc.xml", "upc_01_001.flac"]
        );
        assert!(t.list(&format!("{batch}/none")).await.unwrap().is_empty());
        assert_eq!(
            t.get(&format!("{batch}/upc/upc.xml"), 100).await.unwrap(),
            b"<y/>"
        );
        assert_eq!(
            t.get(&format!("{batch}/upc/missing.xml"), 100).await,
            Err(TransportError::NotFound)
        );
        let dead = SftpTransport {
            port: 1,
            ..from_env().unwrap()
        };
        assert!(matches!(
            dead.put_all(&[Upload::Bytes {
                bytes: vec![1],
                remote: "x/y".into()
            }])
            .await,
            Err(TransportError::Unreachable(_))
        ));
        let _ = std::fs::remove_file(local);
    }
}
